import type {
  CompareResult,
  ProcessingProgress,
  ReportContent,
  ReportDimension,
  ReportHistoryItem,
  ReportSummary,
} from '@cbi/shared-types';

const STARTED = '2026-09-20T10:00:00.000Z';
const ENDED = '2026-09-20T10:25:00.000Z';

export function makeDimension(overrides: Partial<ReportDimension> = {}): ReportDimension {
  return {
    key: 'nodejs',
    name: 'Node.js',
    category: 'TECHNICAL',
    weight: 40,
    score: 72,
    rationale: 'Explained the event loop clearly and gave a real API example.',
    evidence: [
      {
        id: 'ev1',
        claim: 'Described building a REST API with Express and pagination.',
        strength: 2,
        quote: 'I added cursor pagination because offsets were slow.',
        questionId: 'q2',
        question: 'Tell me about an API you built.',
      },
    ],
    fallback: false,
    ...overrides,
  };
}

export function makeReportContent(overrides: Partial<ReportContent> = {}): ReportContent {
  return {
    schemaVersion: 1,
    header: {
      title: 'Backend Developer',
      companyName: 'Acme Labs',
      mode: 'TEXT',
      language: 'en',
      startedAt: STARTED,
      endedAt: ENDED,
      durationSec: 1500,
      endReason: 'COMPLETED',
    },
    overall: {
      score: 64,
      band: 'READY_WITH_GAPS',
      confidence: {
        level: 'MEDIUM',
        value: 0.6,
        factors: {
          independentQuestions: 0.8,
          practicalEvidence: 0.5,
          consistency: 0.7,
          completeness: 0.45,
        },
      },
      assessedWeight: 0.75,
    },
    summary: 'You explain backend concepts well; database design needs more practice.',
    dimensions: [
      makeDimension({
        key: 'sql',
        name: 'SQL',
        weight: 25,
        score: 48,
        rationale: 'Knew joins but struggled with indexing.',
        evidence: [
          {
            id: 'ev2',
            claim: 'Could not explain when an index helps.',
            strength: -1,
            quote: null,
            questionId: 'q3',
            question: 'How would you speed up a slow query?',
          },
        ],
        fallback: true,
      }),
      makeDimension({
        key: 'testing',
        name: 'Testing',
        weight: 15,
        score: null,
        rationale: null,
        evidence: [],
      }),
      makeDimension(),
      makeDimension({
        key: 'communication',
        name: 'Communication',
        category: 'BEHAVIORAL',
        weight: 20,
        score: 80,
        evidence: [],
      }),
    ],
    strengths: [
      { text: 'Your API answers suggest solid hands-on experience.', dimensionKey: 'nodejs' },
    ],
    gaps: [{ text: 'Indexing and query plans seem unfamiliar so far.', dimensionKey: 'sql' }],
    rounds: [
      { type: 'INTRO', state: 'DONE', questions: 2, answered: 2, durationSec: 300 },
      { type: 'TECHNICAL', state: 'DONE', questions: 5, answered: 4, durationSec: 1200 },
    ],
    coverage: [
      { skill: 'Node.js', sources: ['JD', 'RESUME'], inResume: true, assessed: true },
      { skill: 'Docker', sources: ['JD'], inResume: false, assessed: false },
    ],
    plan: {
      next24h: [
        {
          action: 'Read how B-tree indexes work.',
          why: 'Indexing was your weakest answer.',
          dimensionKey: 'sql',
        },
      ],
      next3Days: [
        {
          action: 'Optimise three slow queries on a sample database.',
          why: 'Practice turns the theory into examples you can talk about.',
          dimensionKey: 'sql',
        },
      ],
      next7Days: [
        {
          action: 'Write integration tests for your REST API.',
          why: 'Testing was not assessed yet.',
          dimensionKey: 'testing',
        },
      ],
    },
    previous: null,
    transcript: [
      {
        seq: 1,
        roundType: 'INTRO',
        question: 'Tell me about yourself.',
        answer: 'I am a final-year student who builds APIs.',
      },
    ],
    disclaimer:
      'This report was generated by AI from your answers. It is practice feedback, not a hiring decision.',
    ...overrides,
  };
}

export function makeReport(
  overrides: Partial<Omit<ReportSummary, 'content'>> & { content?: Partial<ReportContent> } = {},
): ReportSummary {
  const { content, ...rest } = overrides;
  return {
    sessionId: 'int1',
    revision: 0,
    generatedAt: '2026-09-20T10:30:00.000Z',
    content: makeReportContent(content),
    pdfReady: true,
    credit: 'CONSUMED',
    ...rest,
  };
}

export function makeHistoryItem(overrides: Partial<ReportHistoryItem> = {}): ReportHistoryItem {
  return {
    sessionId: 'int1',
    title: 'Backend Developer',
    companyName: 'Acme Labs',
    roleKey: 'backend-developer',
    mode: 'TEXT',
    language: 'en',
    overall: 64,
    band: 'READY_WITH_GAPS',
    confidence: 'MEDIUM',
    durationSec: 1500,
    endedAt: ENDED,
    ...overrides,
  };
}

export function makeProgress(overrides: Partial<ProcessingProgress> = {}): ProcessingProgress {
  return {
    stage: 'SCORE_DIMENSIONS',
    status: 'RUNNING',
    completedStages: ['FINALIZE_TRANSCRIPT', 'EXTRACT_EVIDENCE'],
    reportReady: false,
    ...overrides,
  };
}

export function makeCompare(overrides: Partial<CompareResult> = {}): CompareResult {
  return {
    attempts: [
      { sessionId: 'int0', endedAt: '2026-09-10T10:25:00.000Z', overall: 50, confidence: 'LOW' },
      { sessionId: 'int1', endedAt: ENDED, overall: 64, confidence: 'MEDIUM' },
    ],
    dimensions: [
      { key: 'nodejs', name: 'Node.js', scores: [60, 72], delta: 12 },
      { key: 'sql', name: 'SQL', scores: [55, 48], delta: -7 },
      { key: 'testing', name: 'Testing', scores: [null, null], delta: null },
    ],
    ...overrides,
  };
}
